image:
  repository: wolveix/satisfactory-server
  pullPolicy: IfNotPresent
  tag: v1.8.5@sha256:8a968aa693716ca88da8680409c54f2f3daff71a76fb2ac2c990a782673a81e8
persistence:
  config:
    enabled: true
    mountPath: "/config"
  tmp-dumps:
    enabled: true
    type: emptyDir
    mountPath: "/tmp/dumps"
service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        targetPort: 7777
        port: 7777
        protocol: udp
      maintcp:
        enabled: true
        targetPort: "{{ .Values.service.main.ports.main.targetPort }}"
        port: "{{ .Values.service.main.ports.main.port }}"
        protocol: tcp
portal:
  open:
    enabled: false
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            AUTOSAVENUM: 5
            DEBUG: false
            DISABLESEASONALEVENTS: false
            LOG: false
            MAXOBJECTS: 2162688
            MAXPLAYERS: 4
            MAXTICKRATE: 30
            ROOTLESS: false
            SERVERGAMEPORT: "{{ .Values.service.main.ports.main.targetPort }}"
            SERVERIP: "0.0.0.0"
            SERVERSTREAMING: true
            SKIPUPDATE: false
            STEAMBETA: false
            TIMEOUT: 30
            VMOVERRIDE: false
